name: Validate Telemetry Samples

on:
  push:
    branches: [ main ]

env:
  LIGHTBEND_COMMERCIAL_MVN: ${{ secrets.LIGHTBEND_COMMERCIAL_MVN }}
  LIGHTBEND_COMMERCIAL_IVY: ${{ secrets.LIGHTBEND_COMMERCIAL_IVY }}

jobs:
  validate-java-sample:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9

      - uses: actions/cache@v2.1.3
        with:
          path: ~/.m2/repository
          key: maven-repo-telemetry-${{ hashFiles('**/telemetry-sample/pom.xml') }}
          restore-keys: maven-repo-telemetry-

      - name: "Telemetry Sample (Java)"
        run: scripts/mvn-test.sh ./docs-source/docs/modules/telemetry/examples/telemetry-sample

  validate-scala-sample:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9

      - name: Cache Coursier cache
        uses: coursier/cache-action@v5

      - name: "Telemetry Sample (Scala)"
        run: scripts/sbt-test.sh ./docs-source/docs/modules/telemetry/examples/telemetry-sample
